version: '3.8'

services:
  mercur-e:
    build: .
    container_name: mercur-e
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./private-key.pem:/app/private-key.pem:ro
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy with TLS
  nginx:
    image: nginx:alpine
    container_name: mercur-e-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mercur-e
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
